twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        image_public: '%image_public%'

when@test:
    twig:
        strict_variables: true
